package com.aspire.onlinebookstore;

public class AdminAuthorities {
	public void goToManageBooks() {
		System.out.println("ULYSSES\r\n"
				+ "by James Joyce\r\n"
				+ "THE GREAT GATSBY\r\n"
				+ "by F. Scott Fitzgerald\r\n"
				+ "A PORTRAIT OF THE ARTIST AS A YOUNG MAN\r\n"
				+ "by James Joyce\r\n"
				+ "LOLITA\r\n"
				+ "by Vladimir Nabokov\r\n"
				+ "BRAVE NEW WORLD\r\n"
				+ "by Aldous Huxley\r\n"
				+ "THE SOUND AND THE FURY\r\n"
				+ "by William Faulkner\r\n"
				+ "CATCH-22\r\n"
				+ "by Joseph Heller\r\n"
				+ "DARKNESS AT NOON\r\n"
				+ "by Arthur Koestler\r\n"
				+ "SONS AND LOVERS\r\n"
				+ "by D.H. Lawrence\r\n"
				+ "THE GRAPES OF WRATH\r\n"
				+ "by John Steinbeck\r\n"
				+ "UNDER THE VOLCANO\r\n"
				+ "by Malcolm Lowry\r\n"
				+ "THE WAY OF ALL FLESH\r\n"
				+ "by Samuel Butler\r\n"
				+ "1984\r\n"
				+ "by George Orwell\r\n"
				+ "I, CLAUDIUS\r\n"
				+ "by Robert Graves\r\n"
				+ "TO THE LIGHTHOUSE\r\n"
				+ "by Virginia Woolf\r\n"
				+ "AN AMERICAN TRAGEDY\r\n"
				+ "by Theodore Dreiser\r\n"
				+ "THE HEART IS A LONELY HUNTER\r\n"
				+ "by Carson McCullers\r\n"
				+ "SLAUGHTERHOUSE-FIVE\r\n"
				+ "by Kurt Vonnegut\r\n"
				+ "INVISIBLE MAN\r\n"
				+ "by Ralph Ellison\r\n"
				+ "NATIVE SON\r\n"
				+ "by Richard Wright\r\n"
				+ "HENDERSON THE RAIN KING\r\n"
				+ "by Saul Bellow\r\n"
				+ "APPOINTMENT IN SAMARRA\r\n"
				+ "by John O’Hara\r\n"
				+ "U.S.A.(trilogy)\r\n"
				+ "by John Dos Passos\r\n"
				+ "WINESBURG, OHIO\r\n"
				+ "by Sherwood Anderson\r\n"
				+ "A PASSAGE TO INDIA\r\n"
				+ "by E.M. Forster\r\n"
				+ "THE WINGS OF THE DOVE\r\n"
				+ "by Henry James\r\n"
				+ "THE AMBASSADORS\r\n"
				+ "by Henry James\r\n"
				+ "TENDER IS THE NIGHT\r\n"
				+ "by F. Scott Fitzgerald\r\n"
				+ "THE STUDS LONIGAN TRILOGY\r\n"
				+ "by James T. Farrell\r\n"
				+ "THE GOOD SOLDIER\r\n"
				+ "by Ford Madox Ford\r\n"
				+ "ANIMAL FARM\r\n"
				+ "by George Orwell\r\n"
				+ "THE GOLDEN BOWL\r\n"
				+ "by Henry James\r\n"
				+ "SISTER CARRIE\r\n"
				+ "by Theodore Dreiser\r\n"
				+ "A HANDFUL OF DUST\r\n"
				+ "by Evelyn Waugh\r\n"
				+ "AS I LAY DYING\r\n"
				+ "by William Faulkner\r\n"
				+ "ALL THE KING’S MEN\r\n"
				+ "by Robert Penn Warren\r\n"
				+ "THE BRIDGE OF SAN LUIS REY\r\n"
				+ "by Thornton Wilder\r\n"
				+ "HOWARDS END\r\n"
				+ "by E.M. Forster\r\n"
				+ "GO TELL IT ON THE MOUNTAIN\r\n"
				+ "by James Baldwin\r\n"
				+ "THE HEART OF THE MATTER\r\n"
				+ "by Graham Greene\r\n"
				+ "LORD OF THE FLIES\r\n"
				+ "by William Golding\r\n"
				+ "DELIVERANCE\r\n"
				+ "by James Dickey\r\n"
				+ "A DANCE TO THE MUSIC OF TIME (series)\r\n"
				+ "by Anthony Powell\r\n"
				+ "POINT COUNTER POINT\r\n"
				+ "by Aldous Huxley\r\n"
				+ "THE SUN ALSO RISES\r\n"
				+ "by Ernest Hemingway\r\n"
				+ "THE SECRET AGENT\r\n"
				+ "by Joseph Conrad\r\n"
				+ "NOSTROMO\r\n"
				+ "by Joseph Conrad\r\n"
				+ "THE RAINBOW\r\n"
				+ "by D.H. Lawrence\r\n"
				+ "WOMEN IN LOVE\r\n"
				+ "by D.H. Lawrence\r\n"
				+ "TROPIC OF CANCER\r\n"
				+ "by Henry Miller\r\n"
				+ "THE NAKED AND THE DEAD\r\n"
				+ "by Norman Mailer\r\n"
				+ "PORTNOY’S COMPLAINT\r\n"
				+ "by Philip Roth\r\n"
				+ "PALE FIRE\r\n"
				+ "by Vladimir Nabokov\r\n"
				+ "LIGHT IN AUGUST\r\n"
				+ "by William Faulkner\r\n"
				+ "ON THE ROAD\r\n"
				+ "by Jack Kerouac\r\n"
				+ "THE MALTESE FALCON\r\n"
				+ "by Dashiell Hammett\r\n"
				+ "PARADE’S END\r\n"
				+ "by Ford Madox Ford\r\n"
				+ "THE AGE OF INNOCENCE\r\n"
				+ "by Edith Wharton\r\n"
				+ "ZULEIKA DOBSON\r\n"
				+ "by Max Beerbohm\r\n"
				+ "THE MOVIEGOER\r\n"
				+ "by Walker Percy\r\n"
				+ "DEATH COMES FOR THE ARCHBISHOP\r\n"
				+ "by Willa Cather\r\n"
				+ "FROM HERE TO ETERNITY\r\n"
				+ "by James Jones\r\n"
				+ "THE WAPSHOT CHRONICLES\r\n"
				+ "by John Cheever\r\n"
				+ "THE CATCHER IN THE RYE\r\n"
				+ "by J.D. Salinger\r\n"
				+ "A CLOCKWORK ORANGE\r\n"
				+ "by Anthony Burgess\r\n"
				+ "OF HUMAN BONDAGE\r\n"
				+ "by W. Somerset Maugham\r\n"
				+ "HEART OF DARKNESS\r\n"
				+ "by Joseph Conrad\r\n"
				+ "MAIN STREET\r\n"
				+ "by Sinclair Lewis\r\n"
				+ "THE HOUSE OF MIRTH\r\n"
				+ "by Edith Wharton\r\n"
				+ "THE ALEXANDRIA QUARTET\r\n"
				+ "by Lawrence Durrell\r\n"
				+ "A HIGH WIND IN JAMAICA\r\n"
				+ "by Richard Hughes\r\n"
				+ "A HOUSE FOR MR BISWAS\r\n"
				+ "by V.S. Naipaul\r\n"
				+ "THE DAY OF THE LOCUST\r\n"
				+ "by Nathanael West\r\n"
				+ "A FAREWELL TO ARMS\r\n"
				+ "by Ernest Hemingway\r\n"
				+ "SCOOP\r\n"
				+ "by Evelyn Waugh");
	}
	public void goToManageOrders(){
		
	}
	public void goToManageUser() {
		
	}
	
}
